services:
  #############################################################
  #                                                           #
  # application web we-cine-2021 : interface                  #
  #                                                           #
  #############################################################
  propal_we_cine_2021_webapp:
    hostname: 'propal.we.cine.2021.webapp'
    build: '../webapp'
    container_name: propal-we-cine-2021-webapp-instance
    restart: always
    ports:
      - "8880:80"
    volumes:
      - "$PWD/../webapp:/var/www/html"
      - "$PWD/php8/log/apache2/webapp:/var/log/apache2"
      - "$PWD/php8/share/webapp:/share"
    environment:
      # variables d'environnement qui alimente directement le .env
      APP_ENV: dev
      APP_SECRET: 07200d027b54861b75589fbefeeacc4b
      TMDB_API_KEY: 42815b3ceb6a8041e05fb6eea8cffc6f
      TMDB_REMOTE_URL: "https://api.themoviedb.org/"
