services:
  #############################################################
  #                                                           #
  # RABBIT MQ                                                 #
  #                                                           #
  #############################################################
  propal_we_cine_2021_rabbitmq:
    hostname: 'propal.we.cine.2021.rabbitmq'
    build: './rabbitmq'
    container_name: propal-we-cine-2021-rabbitmq-instance
    ports: 
      - '5672:5672' 
      - '15672:15672' 
    volumes: 
      - propal-we-cine-2021-rabbitmq-data:/var/lib/rabbitmq/ 
      - propal-we-cine-2021-rabbitmq-log:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  #############################################################
  #                                                           #
  # REDIS                                                     #
  #                                                           #
  #############################################################
  propal_we_cine_2021_redis:
    hostname: 'propal.we.cine.2021.redis'
    image: 'redis:latest'
    container_name: propal-we-cine-2021-redis-instance
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - propal-we-cine-2021-cache:/data

  #############################################################
  #                                                           #
  # application web we-cine-2021 : interface                  #
  #                                                           #
  #############################################################
  propal_we_cine_2021_webapp:
    hostname: 'propal.we.cine.2021.webapp'
    build: '../webapp'
    container_name: propal-we-cine-2021-webapp-instance
    restart: always
    ports:
      - "8880:80"
    volumes:
      - "$PWD/../webapp:/var/www/html"
      - "$PWD/php8/log/apache2/webapp:/var/log/apache2"
      - "$PWD/php8/share/webapp:/share"
    environment:
      # variables d'environnement qui alimente directement le .env
      APP_ENV: dev
      APP_SECRET: 07200d027b54861b75589fbefeeacc4b
      TMDB_API_KEY: 42815b3ceb6a8041e05fb6eea8cffc6f
      TMDB_REMOTE_URL: "https://api.themoviedb.org/"
      DATABASE_TYPE: "postgresql"
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: "propal.we.cine.2021.postgres" 
      DATABASE_PORT: 5432
      DATABASE_NAME: "propal_we_cine_2021"
      MINIO_HOST: "http://propal-we-cine-2021-minio-instance:9000"
      MINIO_ACCESS_KEY: "mYOCgRwJ4Y0Y1h631j5K"
      MINIO_SECRET_KEY: "jQSlr5ydkAD4z5x6gRPtEQeBdNJwN5sohtjR0Aww"
      MINIO_READER_ACCESS_KEY: "mYOCgRwJ4Y0Y1h631j5K"
      MINIO_READER_SECRET_KEY: "jQSlr5ydkAD4z5x6gRPtEQeBdNJwN5sohtjR0Aww"
      MINIO_BUCKET: "documents"
      MINIO_JS_HOSTNAME: "localhost"
      MINIO_JS_PORT: 9000
      MINIO_JS_USE_SSL: false
      RABBITMQ_TRANSPORT_DSN: "amqp://admin:admin@propal_we_cine_2021_rabbitmq:5672"
      DOCTRINE_TRANSPORT_DSN: "doctrine://default"
  #############################################################
  #                                                           #
  # Postgres : base de données                                #
  #                                                           #
  #############################################################
  propal_we_cine_2021_postgres:
    hostname: 'propal.we.cine.2021.postgres'
    container_name: 'propal-we-cine-2021-postgres-instance'
    build: 'postgres'
    restart: 'always'
    ports:
      - "9942:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "propal-we-cine-2021-postgres-data:/var/lib/postgresql/data"
  #############################################################
  #                                                           #
  # Pgadmin                                                   #
  #                                                           #
  #############################################################
  propal_we_cine_2021_pgadmin:
    hostname: 'propal.we.cine.2021.pgadmin'
    image: dpage/pgadmin4
    container_name: propal-we-cine-2021-pgadmin-instance
    restart: always
    ports:
      - "8881:80"
    depends_on:
      - propal_we_cine_2021_postgres
    volumes:
      - "propal-we-cine-2021-pgadmin:/var/lib/pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@noname.fr
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_LISTEN_PORT: 80
      GUNICORN_THREADS: 1
  #############################################################
  #                                                           #
  # Minio                                                     #
  #                                                           #
  #############################################################
  propal_we_cine_2021_minio:
    image: 'minio/minio:latest'
    container_name: 'propal-we-cine-2021-minio-instance'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_DATA_DIR: /data/minio
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
#      MINIO_API_PORT_NUMBER: 9000
#      MINIO_CONSOLE_PORT_NUMBER: 8900
      MINIO_DEFAULT_BUCKETS: documents
    volumes:
      - 'propal-we-cine-2021-minio:/data/minio'
    command: 'minio server /data/minio --console-address ":9001"'
    restart: unless-stopped

volumes:
  propal-we-cine-2021-minio:
  propal-we-cine-2021-pgadmin:
  propal-we-cine-2021-postgres-data:
  propal-we-cine-2021-cache:
  propal-we-cine-2021-rabbitmq-data:
  propal-we-cine-2021-rabbitmq-log: