services:
  #############################################################
  #                                                           #
  # application web we-cine-2021 : interface                  #
  #                                                           #
  #############################################################
  propal_we_cine_2021_webapp:
    hostname: 'propal.we.cine.2021.webapp'
    build: '../webapp'
    container_name: propal-we-cine-2021-webapp-instance
    restart: always
    ports:
      - "8880:80"
    volumes:
      - "$PWD/../webapp:/var/www/html"
      - "$PWD/php8/log/apache2/webapp:/var/log/apache2"
      - "$PWD/php8/share/webapp:/share"
    environment:
      # configuration de la base de donnée pour l'application symfony
      APP_ENV: dev
      APP_SECRET: 07200d027b54861b75589fbefeeacc4b
      TMDB_PASSWORD: Mhpc5l8RU7nMiiY8z9FQ
      TMDB_USERNAME: yanroussel
